method: plan
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90"
  val_split: .1
  preshuffle: False
  max_seq_len: 380
  augment: True
  augmentation:
    subsequence_rate: 0.8
    image_aug: 0
    input_noise: .8
  max_count: 50
  full_seq: False
  full_seq_val: False

model:
  goal_mode: one-hot
  vae_path: /home/mrl/Documents/Projects/tskill/out/PegInsertion/VAE/014
  hidden_dim: 512
  dropout : 0.1
  nheads : 16
  dim_feedforward : 2048
  enc_layers : 4
  dec_layers : 6
  pre_norm : False
  conditional_decode: False
  conditional_plan: True # Alt

loss:
  z_weight: 1
  act_weight: 1

training:
  out_dir: out/PegInsertion/Plan/031
  train_vae: True
  max_it: 100000
  batch_size: 16
  batch_size_val: 16
  batch_size_alt: 8
  fraction_alt: 0.0
  val_alt: False
  print_every: 50
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 2000
  model_selection_metric: z_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0
  lr: 0.0001
  lr_decay: 0.98
  lr_warmup_epochs: 0
  weight_decay: 0.0001
  use_precalc: True
