method: plan
notes: Lower param planner with lower param vae w KL 0.01. Less demos too.
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos_256.h5
  val_split: .625
  preshuffle: False
  max_seq_len: 200
  augment: True
  augmentation:
    subsequence_rate: 0.75
    image_aug: 0
  max_count: 80
  indices:
  full_seq: True

model:
  vae_path: /home/mrl/Documents/Projects/tskill/out/PegInsertion/VAE/058
  hidden_dim: 256
  dropout : 0.1
  nheads : 4
  dim_feedforward : 256
  enc_layers : 3
  dec_layers : 5
  pre_norm : False
  conditional_decode: False
  conditional_plan: False # Alt

loss:
  z_weight: 1
  act_weight: 1

training:
  out_dir: out/PegInsertion/Plan/025
  train_vae: True
  max_it: 100000
  batch_size: 24
  batch_size_val: 4
  batch_size_alt: 6
  fraction_alt: 0.25
  val_alt: True
  print_every: 25
  visualize_every: 2000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 2000
  model_selection_metric: act_plan_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0
  lr: 0.00005
  lr_decay: 0
  weight_decay: 0.0001
  use_precalc: True
