method: plan
notes: Planning run with higher subsequencing, as well as single step decoder autoregression (only tgt self attention)
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos_256.h5
  val_split: .1
  preshuffle: False
  max_seq_len: 200
  augment: True
  augmentation:
    subsequence_rate: 0.67
    image_aug: 0
  max_count: 50
  indices:
  full_seq: True

model:
  vae_path: /home/mrl/Documents/Projects/tskill/out/PegInsertion/VAE/053
  hidden_dim: 256
  dropout : 0.1
  nheads : 4
  dim_feedforward : 512
  enc_layers : 4
  dec_layers : 6
  pre_norm : False
  conditional_decode: False

loss:
  z_weight: 2
  act_weight: 1

training:
  out_dir: out/PegInsertion/Plan/011
  train_vae: True
  max_it: 30000
  batch_size: 10
  batch_size_val: 10
  print_every: 25
  visualize_every: 500
  checkpoint_every: 500
  validate_every: 300
  backup_every: 1000
  model_selection_metric: act_plan_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0
  lr: 0.00003
  lr_decay: 0
  weight_decay: 0.0001
  gradient_accumulation: 1
  use_precalc: True
