method: plan
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90/KITCHEN_SCENE1_open_the_top_drawer_of_the_cabinet_and_put_the_bowl_in_it_demo.hdf5"
  val_split: .1
  preshuffle: False
  max_seq_len: 380
  augment: True
  augmentation:
    subsequence_rate: 0.8
    image_aug: 0
    input_noise: 0.8
  max_count: 50
  full_seq: False
  full_seq_val: False

model:
  goal_mode: one-hot
  vae_path: /home/mrl/Documents/Projects/tskill/out/VAE/047
  hidden_dim: 128
  dropout : 0.1
  nheads : 8
  dim_feedforward : 1024
  enc_layers : 2
  dec_layers : 3
  pre_norm : False
  conditional_plan: False # Alt

loss:
  z_weight: 1
  act_weight: 1
  dist_weight: 0

training:
  out_dir: out/Plan/010
  train_vae: True
  max_it: 50000
  batch_size: 6
  batch_size_val: 6
  batch_size_alt: 4
  fraction_alt: 0.0
  val_alt: False
  print_every: 50
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 500
  backup_every: 500
  model_selection_metric: act_plan_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0000
  lr: 0.0001
  lr_decay: 0.9995
  lr_warmup_epochs: 2
  weight_decay: 0.0001
  use_precalc: True
