method: plan
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90"
  val_split: .1
  preshuffle: False
  max_seq_len: 380
  augment: True
  augmentation:
    subsequence_rate: 0.8
    image_aug: 0
    input_noise: 0.8
  max_count: 50
  full_seq: False
  full_seq_val: False

model:
  goal_mode: one-hot
  vae_path: /home/mrl/Documents/Projects/tskill/out/PegInsertion/VAE/016
  hidden_dim: 512
  dropout : 0.1
  nheads : 8
  dim_feedforward : 512
  enc_layers : 2
  dec_layers : 3
  pre_norm : False
  conditional_decode: False
  conditional_plan: True # Alt

loss:
  z_weight: .1
  act_weight: 0
  dist_weight: 0

training:
  out_dir: out/Plan/001
  train_vae: False
  max_it: 50000
  batch_size: 24
  batch_size_val: 24
  batch_size_alt: 8
  fraction_alt: 0.0
  val_alt: False
  print_every: 50
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 2000
  model_selection_metric: z_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0
  lr: 0.00003
  lr_decay: 0.999
  lr_warmup_epochs: 2
  weight_decay: 0.0001
  use_precalc: True
