method: plan
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90/"
  val_split: .04
  preshuffle: False
  max_seq_len: 380
  augment: True
  augmentation:
    subsequence_rate: 0.75
    image_aug: 0.
    input_noise: 0.
  max_count: 50
  full_seq: False
  full_seq_val: False

model:
  goal_mode: clip
  vae_path: /home/mrl/Documents/Projects/tskill/out/VAE/061
  hidden_dim: 512
  dropout : 0.1
  nheads : 8
  dim_feedforward : 2048
  enc_layers : 2
  dec_layers : 6
  obs_history: 2
  pre_norm : False
  conditional_plan: True
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine

loss:
  z_weight: 1
  act_weight: 0

training:
  out_dir: out/Plan/025
  train_vae: False
  max_it: 50000
  batch_size: 16
  batch_size_val: 2
  batch_size_alt: 4
  fraction_alt: 0.0
  val_alt: False
  print_every: 100
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 1000
  backup_every: 1000
  model_selection_metric: z_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0000
  lr: 0.0001
  lr_decay: 0.999
  lr_warmup_epochs: 2
  weight_decay: 0.0001
  use_precalc: True
