method: plan
notes: No augmentation
data:
  mode: libero
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos_c256.h5
  val_split: .1
  preshuffle: False
  max_seq_len: 200
  augment: False
  augmentation:
    subsequence_rate: 0.75
    image_aug: 0
    input_noise: 0
  max_count: 100
  full_seq: True
  # goal_mode: image

model:
  vae_path: /home/mrl/Documents/Projects/tskill/out/PegInsertion/VAE/001
  hidden_dim: 256
  dropout : 0.2
  nheads : 8
  dim_feedforward : 1024
  enc_layers : 4
  dec_layers : 6
  pre_norm : False
  conditional_decode: False # Alt
  conditional_plan: False # Alt

loss:
  z_weight: 1
  act_weight: 1

training:
  out_dir: out/PegInsertion/Plan/002
  train_vae: True
  max_it: 100000
  batch_size: 12
  batch_size_val: 24
  batch_size_alt: 6
  fraction_alt: 0
  val_alt: False
  print_every: 50
  visualize_every: 2000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 2000
  model_selection_metric: act_plan_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0
  lr: 0.00003
  lr_decay: 0
  weight_decay: 0.0001
  use_precalc: True
