method: skill
notes: Test continue training from 31 with 2 workers and precalculated image features.
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos_256.h5
  val_split: .1
  preshuffle: False
  max_seq_len: 200
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False
  augment: True
  augmentation:
    subsequence_rate: 0.25
    seq_masking_rate: 0.1
    type_masking_rate: 0
    image_aug: 0
    input_noise: False
    val_augmentation: False
  max_count: 50
  indices:
  full_seq: True

model:
  state_dim : 9
  action_dim : 8
  z_dim : 128
  hidden_dim: 256
  max_skill_len: 10
  single_skill: True
  conditional_decode: False
  
  encoder:  
    dropout : 0.1
    nheads : 4
    dim_feedforward : 256
    enc_layers : 3
    dec_layers : 2
    pre_norm : False
  
  decoder:
    dropout : 0.1
    nheads : 4
    dim_feedforward : 256
    enc_layers : 2
    dec_layers : 3
    pre_norm : False 
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine

loss:
  kl_weights: 0.0001

training:
  out_dir: out/PegInsertion/032
  max_it: 10000
  batch_size: 8
  batch_size_val: 8
  print_every: 25
  visualize_every: 200
  checkpoint_every: 200
  validate_every: 200
  backup_every: 500
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0000
  lr: 0.00003
  lr_decay: 0
  weight_decay: 0.0001
  gradient_accumulation: 1
  use_precalc: True
