method: skill
data:
  dataset: skill
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  padding: 0.0
  type: geom
model:
  action_dim: 26
  state_dim: 128
  latent_dim: 128

  state_encoder_kwargs:
    ckpt_file: None


training:
  out_dir: out/default
  batch_size: 1
  batch_size_val: 1
  pos_weight: 5
  print_every: 200
  visualize_every: 1000
  visualize_total: 15
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: true
  remove_wall: false
  model_file: model_best.pt
