method: skill
notes: For use as first baseline. Very small network, about 50 training demos. No KL or stt lr. No augmentation. Skill length is 1.
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos.h5
  val_split: .16
  preshuffle: True
  max_seq_len: 200
  action_scaling: normal
  state_scaling: 1
  augment: False
  augmentation:
    subsequence_rate: 1
    masking_rate: 0
    val_augmentation: False
  max_count: 60
  indices:

model:
  state_dim : 9
  action_dim : 7 # TODO GRIPPER FIX
  max_skill_len : 1
  z_dim : 64
  hidden_dim: 128
  
  encoder:  
    dropout : 0.1
    nheads : 1
    dim_feedforward : 256 
    enc_layers : 1 
    dec_layers : 1
    pre_norm : False  
  
  decoder:
    dropout : 0.1
    nheads : 1 
    dim_feedforward : 256 
    enc_layers : 1 
    dec_layers : 1 
    pre_norm : False 
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine 
    masks: False 
    dilation: False 

loss:
  kl_weights: 0.000

training:
  out_dir: out/PegInsertion/001
  max_it: 1000
  batch_size: 4
  batch_size_val: 4
  print_every: 10
  visualize_every: 10
  checkpoint_every: 1000
  validate_every: 100
  backup_every: 200
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
  lr_state_encoder: 0.00
  lr: 0.01
  lr_decay: 0.95
  weight_decay: 0.0001
