method: skill
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90/" 
  val_split: .04
  preshuffle: False
  max_seq_len: 380
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False
  augment: True
  augmentation:
    subsequence_rate: 0.8
    image_aug: 0.
    input_noise: 0.
  max_count: 50
  indices:
  full_seq: False
  full_seq_val: False

model:
  state_dim : 9 # LIBERO is 9, MS is 18
  action_dim : 7 # LIBERO is 7, MS is 8
  alpha: [7,5,5,5]
  hidden_dim: 512
  max_skill_len: 8
  encoder_obs: 4
  decoder_obs: 4
  goal_mode: one-hot

  encoder:
    dropout : 0.1
    nheads : 8
    dim_feedforward : 2048
    enc_layers : 0
    dec_layers : 6
    pre_norm : False
  
  decoder:
    dropout : 0.1
    nheads : 8
    dim_feedforward : 2048
    enc_layers : 0
    dec_layers : 6
    pre_norm : False
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine

training:
  out_dir: out/VAE/058
  max_it: 30000
  batch_size: 16
  batch_size_val: 6
  print_every: 100
  visualize_every: 2000
  checkpoint_every: 1000
  validate_every: 1000
  backup_every: 1000
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0000
  lr: 0.00003
  lr_decay: 0.999
  lr_warmup_epochs: 0
  weight_decay: 0.0001
  gradient_accumulation: 1
  use_precalc: True
