method: skill
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos.h5
  val_split: 0.1
  preshuffle: True
  max_seq_len: 200

model:
  state_dim : 9
  action_dim : 8
  max_skill_len : 10
  z_dim : 32
  hidden_dim: 256
  
  encoder:  
    dropout : 0.1
    nheads : 8
    dim_feedforward : 1024 
    enc_layers : 4 
    dec_layers : 6 
    pre_norm : False  
  
  decoder:
    dropout : 0.1 
    nheads : 8 
    dim_feedforward : 1024 
    enc_layers : 4 
    dec_layers : 6 
    pre_norm : False 
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine 
    masks: False 
    dilation: False 

loss:
  kl_weights: 0.01

training:
  out_dir: out/PegInsertion/test
  max_it: 1000
  batch_size: 10
  batch_size_val: 10
  print_every: 1
  visualize_every: 10
  visualize_total: 15
  checkpoint_every: 100
  validate_every: 10
  backup_every: 100
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
  lr_state_encoder: 0.000
  lr: 0.001
  weight_decay: 0.0001
