method: skill
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90/KITCHEN_SCENE1_open_the_top_drawer_of_the_cabinet_and_put_the_bowl_in_it_demo.hdf5"
  val_split: .1
  preshuffle: False
  max_seq_len: 380
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False
  augment: True
  augmentation:
    subsequence_rate: 0.8
    image_aug: 0.
    input_noise: 0
  max_count: 50
  indices:
  full_seq: False
  full_seq_val: False

model:
  state_dim : 9 # LIBERO is 9, MS is 18
  action_dim : 7 # LIBERO is 7, MS is 8
  z_dim : 8
  hidden_dim: 256
  max_skill_len: 10
  conditional_decode: False
  autoregressive_decode: True
  encode_state: True
  encoder_is_causal: True
  
  encoder:
    dropout : 0.1
    nheads : 8
    dim_feedforward : 1024
    enc_layers : 0
    dec_layers : 6
    pre_norm : False
  
  decoder:
    dropout : 0.1
    nheads : 8
    dim_feedforward : 1024
    enc_layers : 0
    dec_layers : 4
    pre_norm : False
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine

loss:
  kl_weight: .001
  # kl_weight_final: 0.01
  # cont_weight: 0.000

training:
  out_dir: out/VAE/030
  max_it: 25000
  batch_size: 8
  batch_size_val: 8
  print_every: 50
  visualize_every: 2000
  checkpoint_every: 1000
  validate_every: 500
  backup_every: 500
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.00001
  lr: 0.00002
  lr_decay: 0.9995
  lr_warmup_epochs: 10
  weight_decay: 0.0001
  gradient_accumulation: 1
  use_precalc: False
