method: skill
notes: Base with more heads and with qvel in state.
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos_256.h5
  val_split: .1
  preshuffle: False
  max_seq_len: 200
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False
  augment: False
  augmentation:
    subsequence_rate: 0.33
    seq_masking_rate: 0.1
    type_masking_rate: 0
  max_count: 50
  indices:
  full_seq: True

model:
  state_dim : 18
  action_dim : 8
  z_dim : 128
  hidden_dim: 256
  max_skill_len: 10
  conditional_decode: False
  autoregressive_decode: True
  encode_state: True
  encoder_is_causal: True
  
  encoder:  
    dropout : 0.1
    nheads : 8
    dim_feedforward : 512
    enc_layers : 3
    dec_layers : 4
    pre_norm : False
  
  decoder:
    dropout : 0.1
    nheads : 8
    dim_feedforward : 512
    enc_layers : 3
    dec_layers : 5
    pre_norm : False
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine

loss:
  kl_weights: 0.01

training:
  out_dir: out/PegInsertion/VAE/055
  max_it: 1
  batch_size: 8
  batch_size_val: 8
  print_every: 25
  visualize_every: 1001
  checkpoint_every: 1001
  validate_every: 2
  backup_every: 1
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0000
  lr: 0.000003
  lr_decay: 0
  weight_decay: 0.0001
  gradient_accumulation: 1
  use_precalc: True
