method: skill
notes: Same as previous but increased skill length, seq mask rate, and dropout. Increased decoder heads to 4.
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos.h5
  val_split: .1
  preshuffle: False
  max_seq_len: 200
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False
  augment: True
  augmentation:
    subsequence_rate: 0.8
    seq_masking_rate: 0.2
    type_masking_rate: 0.15
    image_aug: 0.5
    input_noise: False
    val_augmentation: False
  max_count: 50
  indices:
  full_seq: True

model:
  state_dim : 9
  action_dim : 8
  z_dim : 128
  hidden_dim: 128
  max_skill_len: 20
  single_skill: True
  
  encoder:  
    dropout : 0.4
    nheads : 2
    dim_feedforward : 256 
    enc_layers : 3
    dec_layers : 2
    pre_norm : False  
  
  decoder:
    dropout : 0.4
    nheads : 4
    dim_feedforward : 256 
    enc_layers : 2
    dec_layers : 3
    pre_norm : False 
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine
    by_cam: True

loss:
  kl_weights: 0.0001

training:
  out_dir: out/PegInsertion/028
  max_it: 8000
  batch_size: 10
  batch_size_val: 10
  print_every: 25
  visualize_every: 100
  checkpoint_every: 100
  validate_every: 100
  backup_every: 250
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
  lr_state_encoder: 0.00001
  lr: 0.00003
  lr_decay: 0
  weight_decay: 0.0001
  gradient_accumulation: 2
