method: skill
notes: Similar to 184 (005) but higher dropout, a bit lower LR decay.
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos.h5
  val_split: .2
  preshuffle: True
  max_seq_len: 200
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False # TODO GRIPPER FIX
  augment: True
  augmentation:
    subsequence_rate: .6
    masking_rate: 0
    val_augmentation: False
  max_count: 50
  indices:

model:
  state_dim : 9
  action_dim : 7 # TODO GRIPPER FIX
  max_skill_len : 1
  z_dim : 64
  hidden_dim: 128
  
  encoder:  
    dropout : 0.3
    nheads : 1
    dim_feedforward : 256 
    enc_layers : 1
    dec_layers : 1
    pre_norm : False  
  
  decoder:
    dropout : 0.3
    nheads : 1
    dim_feedforward : 256 
    enc_layers : 1 
    dec_layers : 1 
    pre_norm : False 
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine 
    masks: False 
    dilation: False 

loss:
  kl_weights: 0.0001

training:
  out_dir: out/PegInsertion/010
  max_it: 3000
  batch_size: 4
  batch_size_val: 4
  print_every: 25
  visualize_every: 100
  checkpoint_every: 100
  validate_every: 75
  backup_every: 200
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
  lr_state_encoder: 0.00
  lr: 0.001
  lr_decay: 0.995
  weight_decay: 0.0001
  gradient_accumulation: 1
