method: skill
data:
  dataset: /home/mrl/Documents/Projects/tskill/data/demos/v0/rigid_body/PegInsertionSide-v0/trajectory.rgbd.pd_joint_delta_pos.json
  val_split: 0.1
  test_split: 0.1
  preshuffle: True
  max_seq_len: 200

model:
  state_dim : 9
  action_dim : 8
  max_skill_len : 10
  z_dim : 32
  hidden_dim: 256
  
  encoder:  
    dropout : 0.1
    nheads : 8
    dim_feedforward : 1024 
    enc_layers : 4 
    dec_layers : 6 
    pre_norm : False  
  
  decoder:
    dropout : 0.1 
    nheads : 8 
    dim_feedforward : 1024 
    enc_layers : 4 
    dec_layers : 6 
    pre_norm : False 
  
  backbone:
    position_embedding: sine 
    backbone_name: resnet18 
    lr_backbone: 0.0001  
    masks: False 
    dilation: False 

loss:
  kl_weights: 1

training:
  out_dir: out/default
  batch_size: 1
  batch_size_val: 1
  pos_weight: 5
  print_every: 200
  visualize_every: 1000
  visualize_total: 15
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: true
  remove_wall: false
  model_file: model_best.pt
