method: skill
notes:
data:
  mode: libero
  dataset: "/home/mrl/Documents/Projects/tskill/LIBERO/libero/datasets/libero_90/KITCHEN_SCENE1_open_the_bottom_drawer_of_the_cabinet_demo.hdf5"
  val_split: .1
  preshuffle: False
  max_seq_len: 330
  action_scaling: normal
  state_scaling: 1
  gripper_scaling: False
  augment: False
  augmentation:
    subsequence_rate: 0.33
    seq_masking_rate: 0.1
    type_masking_rate: 0
  max_count: 50
  indices:
  full_seq: True

model:
  state_dim : 9 # LIBERO is 9, MS is 18
  action_dim : 7 # LIBERO is 7, MS is 8
  z_dim : 128
  hidden_dim: 256
  max_skill_len: 10
  conditional_decode: True
  autoregressive_decode: True
  encode_state: True
  encoder_is_causal: True
  
  encoder:  
    dropout : 0.2
    nheads : 8
    dim_feedforward : 512
    enc_layers : 4
    dec_layers : 6
    pre_norm : False
  
  decoder:
    dropout : 0.2
    nheads : 8
    dim_feedforward : 512
    enc_layers : 4
    dec_layers : 6
    pre_norm : False
  
  state_encoder:
    method: resnet
    backbone_name: resnet18
    position_embedding: sine

loss:
  kl_weights: .001

training:
  out_dir: out/PegInsertion/VAE/003
  max_it: 1
  batch_size: 2
  batch_size_val: 2
  print_every: 25
  visualize_every: 1001
  checkpoint_every: 1001
  validate_every: 2
  backup_every: 1
  model_selection_metric: act_loss
  model_selection_mode: minimize
  n_workers: 2
  n_workers_val: 2
  lr_state_encoder: 0.0000
  lr: 0.000001
  lr_decay: 0
  weight_decay: 0.0001
  gradient_accumulation: 1
  use_precalc: True
